service: fast-chat-v2

services:
  - type: web
    name: fast-chat-server
    env: node
    plan: starter
    buildCommand: cd server && npm install && npm run build
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: fast-chat-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGIN
        value: https://fast-chat-v2.onrender.com

  - type: web
    name: fast-chat-client
    env: static
    plan: starter
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: ./client/dist
    envVars:
      - key: VITE_API_URL
        value: https://fast-chat-server.onrender.com
      - key: VITE_SOCKET_URL
        value: https://fast-chat-server.onrender.com

databases:
  - name: fast-chat-db
    databaseName: fastchat
    user: fastchat_user
    plan: starter

repo: https://github.com/your-username/fast-chat-v2.git
